# Install Python dependencies, run tests, lint, and measure coverage
name: Run Pytest w/ linting and coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test, lint and measure coverage with pytest
      run: |
        pytest --cov-report xml --junitxml=report.xml --cov=sandpiles tests/
    - name: Coverage Report
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-xml-coverage-path: "./coverage.xml"
        junitxml-path: ./report.xml
        github-token: ${{ secrets.GITHUB_TOKEN }}
        default-branch: master
